apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saphira-edge-ingress
  namespace: saphira-sovereign-core
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "saphira-core-srv"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
spec:
  tls:
  - hosts:
    - novaumbrella.com
    secretName: novaumbrella-tls-certs
  rules:
  - host: novaumbrella.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: saphira-core-srv
            port:
              number: 8080
